# This is a basic workflow to help you get started with Actions

name: "FakeRESTApi using Newman Tests"
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: postman/newman
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run API Tests
        run: newman run "FakeRESTApi.postman_collection.json" -e "FakeRESTApi.postman_environment.json" --iteration-data "Data.csv"
