# This workflow will help you to produce an HTML extra test results report

name: FakeRESTApi Newman runner + HTML reporter
on: [push, pull_request]

jobs:
  Running-API-Testing:
    runs-on: ubuntu-latest
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
   # INstall Node on the runner
      - name: Install Node
        uses: actions/setup-node@v2
        with: 
          node-version: '16.x'

    
    # Install the newman command line utility and also install the html extra reporter
      - name: Install newman and the reporter
        run: |
          npm install -g newman
          npm install -g newman-reporter-htmlextra
          
    # Make directory to upload the test results
      - name: Make Directory for HTML Reports
        run: mkdir -p HTMLReports
        
   # Run the POSTMAN collection
      - name: Run the Tests
        run: newman run "FakeRESTApi.postman_collection.json" -e "FakeRESTApi.postman_environment.json" --iteration-data "Data.csv" -r htmlextra --reporter-htmlextra-export HTMLReports/htmlreport.html

    # Upload the contents of Test Results directory to workspace
      - name: Update the run Details
        uses: actions/upload-artifact@v2
        with: 
          name: RunReports
          path: HTMLReports
